import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaults,parseImport,sum,split3} from '../dist/engine.js';
import {bonusPlan,compareBonus,bonusPresets,exportBonus} from '../dist/bonus.js';
import {normalizeSimpleState} from '../dist/policy.js';
const opi2=(r,y=2026)=>r.events.find(e=>e.type==='opi2'&&e.origin===y);
function invariants(r){assert.equal(r.accounting.difference,0);let c=0,b=0;for(const a of r.cashflow){assert.equal(a.net.salary,0);assert.equal(a.net.tai,0);assert.equal(a.net.psu,0);assert.equal(a.netTotal,sum([a.netBeforeSettlement,a.taxSettlement,a.insuranceSettlement]));c+=a.netTotal;b+=a.netBeforeSettlement;assert.equal(a.cumulative,c);assert.equal(a.cumulativeBeforeSettlement,b);assert.equal(a.net.settlement,a.taxSettlement+a.insuranceSettlement);}assert.equal(c,r.totals.netLiquid);assert.equal(b,r.totals.netLiquidBeforeSettlement);assert.equal(r.totals.netLiquid-r.totals.netLiquidBeforeSettlement,r.totals.taxSettlementInPeriod+r.totals.insuranceSettlementInPeriod);for(const a of r.accrual){assert.equal(a.grossTotal,a.gross.opi1+a.gross.opi2);assert.equal(a.netTotal,a.net.opi1+a.net.opi2);}for(const e of r.events.filter(e=>e.type==='opi2')){assert.equal(sum(e.tranches.map(t=>t.net)),e.snapshot.estimatedStockMarketValue);assert.equal(e.net,sum([e.snapshot.estimatedStockMarketValue,...e.settlements.map(t=>t.net)]));}for(const t of r.taxLog){assert.equal(sum(t.allocation.map(a=>a.finalTaxEstimate)),t.incrementTax);assert.equal(sum(t.allocation.map(a=>a.finalInsuranceEstimate)),t.incrementInsurance);}}
test('new defaults and presets use donation0 and370/550/500/518/466 connected-profit assumptions',()=>{const s=defaults();assert.equal(s.opi2Policy.donationRate,0);for(const sc of Object.values(s.scenarios))assert.deepEqual(sc.performance,{2026:370,2027:550,2028:500,2029:518,2030:466});const r=bonusPlan(s);assert.equal(opi2(r).gross,466200000);assert.equal(opi2(r).snapshot.donation,0);assert.equal(r.totals.donation,0);assert.equal(exportBonus(s).assumptions.donationTaxCredit,'미반영 (0% 기부 시 기부금과 기부 세액공제 모두 0원)');assert.equal(bonusPresets(s).basic.totals.netLiquid,r.totals.netLiquid);invariants(r);});
test('all obsolete donation values normalize to0 without changing other input',()=>{for(const rate of [0,.002,.004,.006,.008,.01]){const s=defaults();s.opi2Policy.donationRate=rate;const r=bonusPlan(s),d=exportBonus(s),loaded=normalizeSimpleState(parseImport(JSON.stringify(d)));assert.equal(loaded.opi2Policy.donationRate,0);assert.equal(bonusPlan(loaded).totals.netLiquid,r.totals.netLiquid);assert.equal(opi2(r).snapshot.donation,0);invariants(r);}});
test('old manual gross including0 is ignored, while stored profit survives and donation is0',()=>{for(const value of [0,123456789]){const s=defaults();s.opi2Policy.manualGrossByYear={2026:value};s.opi2Policy.donationRate=.006;s.scenarios.middle.performance[2026]=333;const clean=normalizeSimpleState(parseImport(JSON.stringify(s)));assert.equal(clean.scenarios.middle.performance[2026],333);assert.equal(clean.opi2Policy.donationRate,0);assert.deepEqual(clean.opi2Policy.manualGrossByYear,{});assert.ok(clean.migrationNotice.includes('적용하지'));assert.equal(opi2(bonusPlan(clean)).gross,419580000);}});
test('all divisions and full-year study use original department coefficient and half exactly once',()=>{for(const [division,coefficient]of [['메모리',1],['공통',.7],['파운드리·시스템LSI',.3]]){const s=defaults();s.people[0].division=division;const before=opi2(bonusPlan(s)).gross;assert.equal(before,Math.round(666000000*coefficient));s.people[0].study[2026]=true;const r=bonusPlan(s);assert.equal(opi2(r).gross,before/2);assert.equal(r.accrual[0].gross.opi1,0);assert.equal(r.accrual[0].gross.tai,0);invariants(r);}});
test('performance2026 pays2027, refunds2028February and releases2027/28/29 without adding shares',()=>{const r=bonusPlan(defaults()),e=opi2(r),tax=e.settlements.find(t=>t.kind==='tax'),ins=e.settlements.find(t=>t.kind==='insurance');assert.equal(e.payYear,2027);assert.equal(tax.year,2028);assert.equal(tax.estimatedMonth,2);assert.ok(tax.timingAssumption.includes('삼성 확정 입금일 아님'));assert.equal(ins.estimatedMonth,4);assert.deepEqual(e.tranches.map(t=>t.year),[2027,2028,2029]);assert.deepEqual(e.tranches.map(t=>t.net),split3(e.snapshot.estimatedStockMarketValue));assert.equal(e.snapshot.estimatedNetFractionalShares,e.snapshot.estimatedStockMarketValue/250000);assert.equal(r.cashflow[1].taxSettlement,0);assert.equal(r.cashflow[2].taxSettlement,tax.net);invariants(r);});
test('period2027 excludes2028refund and keeps signed settlement as ending claim',()=>{const s=defaults();s.endYear=2027;const r=bonusPlan(s),e=opi2(r);assert.equal(r.totals.taxSettlementInPeriod,0);assert.ok(r.locked.settlementEvents.some(t=>t.origin===2026&&t.kind==='tax'&&t.year===2028));assert.equal(r.totals.netLiquid,r.totals.netLiquidBeforeSettlement);assert.ok(r.locked.settlementReceivable>0);invariants(r);});
test('negative tax and insurance settlements reduce cash, never clamp to refund or double-deduct',()=>{const s=defaults();s.settings.tax.brackets=s.settings.tax.brackets.map(([cap])=>[cap,.6]);s.settings.tax.health=.1;const r=bonusPlan(s),e=opi2(r);assert.ok(e.identity.settlementTax<0);assert.ok(e.identity.settlementInsurance<0);assert.equal(e.identity.settlementInsurance,e.snapshot.withheldInsurance-e.finalInsuranceEstimate);assert.ok(r.totals.taxExtraPaymentInPeriod>0);assert.ok(r.cashflow.some(a=>a.taxSettlement<0&&a.insuranceSettlement<0));assert.ok(r.totals.netLiquid<r.totals.netLiquidBeforeSettlement);invariants(r);});
test('main aggregate excludes every wage, allowance, TAI and PSU amount while full tax still includes them',()=>{const s=defaults();s.people[0].allowance=1200000;const r=bonusPlan(s),f=r.fullCompensation;assert.ok(f.totals.netLiquid>r.totals.netLiquid);assert.equal(r.totals.netLiquid,f.totals.netLiquid-sum(f.cashflow.map(a=>sum([a.net.salary,a.net.tai,a.net.psu]))));for(const y of r.taxLog){const fy=f.taxLog.find(a=>a.year===y.year);assert.deepEqual(y,fy);}assert.ok(r.taxLog.some(t=>t.allocation.some(a=>a.type==='psu')));invariants(r);});
test('2030 accrual never gets paid, refunded or sold through2030',()=>{const s=defaults(),before=bonusPlan(s);s.scenarios.middle.performance[2030]=800;const r=bonusPlan(s),e=opi2(r,2030);assert.notEqual(r.totals.netAccrual,before.totals.netAccrual);assert.equal(r.totals.netLiquid,before.totals.netLiquid);assert.equal(e.payYear,2031);assert.equal(e.settlements[0].year,2032);invariants(r);});
test('narrowed period preserves prior stock and cash settlements in opening balance',()=>{const s=defaults();s.startYear=2028;const r=bonusPlan(s);assert.equal(r.accrual.length,3);assert.ok(r.opening.total>0);assert.ok(r.cashflow[0].details.some(e=>e.origin===2026&&e.kind==='tax'));invariants(r);});
test('three stored scenarios and zeroPSU preserve annual and cumulative bonus accounting',()=>{const s=defaults();for(const r of Object.values(compareBonus(s)))invariants(r);s.people[0].psuMultiplier=0;const r=bonusPlan(s);assert.equal(r.fullCompensation.people[0].psuShares,0);assert.ok(r.totals.netLiquid>0);invariants(r);});
test('scoped exports identify main and final full-pay summary and normalize obsolete unsupported donation',()=>{const s=defaults(),d=exportBonus(s);assert.equal(d.scope,'OPI1+OPI2');assert.equal(d.resultModel,'automatic_opi1_opi2_dashboard');assert.ok(d.fullCompensationSummary.totals.netLiquid>d.totals.netLiquid);assert.ok(!Object.hasOwn(d.input.opi2Policy,'manualGrossByYear'));assert.ok(d.settlementNotice.includes('실제 전체 연말정산 환급액과 다릅니다'));s.opi2Policy.donationRate=.003;assert.equal(bonusPlan(s).totals.donation,0);});
