import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaults as publicDefaults,defaultPerson,calculate,validationReport,allocate,split3,salaryAt,taxAndInsurance,workDeduction,exportData,parseImport,importConditions,validateState,sum,mul} from '../dist/engine.js';
const copy=x=>JSON.parse(JSON.stringify(x));
function conservation(r){assert.equal(r.people.length,1);assert.equal(r.opening.total+r.totals.netAccrual,r.totals.netLiquid+r.locked.unpaidCash+r.locked.unpaidStock+r.locked.paidLockedStock);for(const p of r.people){for(const e of p.events){assert.equal(sum(e.tranches.map(t=>t.net)),e.net);assert.equal(sum(e.tranches.map(t=>t.gross)),e.gross);assert.equal(e.net+e.deduction,e.gross);assert.ok(Number.isSafeInteger(e.net));}for(const t of p.taxLog){assert.equal(sum(t.allocation.map(e=>e.deduction)),t.increment);assert.equal(t.baseGross-t.baseTax.total+sum(t.allocation.map(e=>e.net)),t.baseGross+t.bonus-t.fullTax.total);}}}
test('individual v2 generic defaults contain one person and no private preset',()=>{const s=defaults();assert.equal(s.schemaVersion,2);assert.equal(s.mode,'individual');assert.equal(s.people.length,1);assert.equal(s.people[0].salary,85000000);assert.equal(s.people[0].allowance,0);assert.deepEqual(s.people[0].study,{});validateState(s);});
test('exact decimals, largest remainder, permutation independence',()=>{assert.equal(mul(85000000,1.05),89250000);assert.deepEqual(split3(100),[34,33,33]);const w=[{id:'a',weight:35},{id:'b',weight:11},{id:'c',weight:79}],a=allocate(81,w);assert.deepEqual(a,allocate(81,[...w].reverse()).reverse());assert.equal(sum(a),81);assert.equal(sum(allocate(-81,w)),-81);});
test('salary growth, cap and generic OPI2 formula',()=>{const s=defaults();assert.deepEqual([2026,2027,2028,2029,2030].map(y=>salaryAt(s.people[0],y,s)),[85000000,89250000,93712500,98398125,103318031]);assert.equal(calculate(s).accrual[0].gross.opi2,490140000);s.people[0].salary=80000000;s.people[0].growth=.1;s.people[0].cap=100000000;assert.deepEqual([2026,2027,2028,2029,2030].map(y=>salaryAt(s.people[0],y,s)),[80000000,88000000,96800000,100000000,100000000]);conservation(calculate(s));});
const fixtures={middle:{cash:[72823356,188421308,353066780,499961016,549026730],total:1663299190},downturn:{cash:[72823356,188421308,353066780,364484479,278350456],total:1257146379},downturnZero:{cash:[72823356,188421308,326708802,336056319,250153847],total:1174163632}};
for(const key of Object.keys(fixtures))test('generic reference scenario '+key,()=>{const s=defaults(),sc=copy(key==='middle'?s.scenarios.middle:s.scenarios.downturn);if(key==='downturnZero')sc.psuMode='zero';const r=calculate(s,sc);assert.deepEqual(r.cashflow.map(c=>c.netTotal),fixtures[key].cash);assert.equal(r.totals.netLiquid,fixtures[key].total);conservation(r);assert.ok(validationReport().find(v=>v.key===key).checks.some(c=>c.warning));});
test('study keeps salary, zeros OPI1/TAI and origin coefficient survives next-year delivery',()=>{const s=defaults(),normal=calculate(s);s.people[0].study[2029]=true;const r=calculate(s),a=r.accrual[3];assert.equal(a.gross.opi1,0);assert.equal(a.gross.tai,0);assert.equal(a.salary,normal.accrual[3].salary);assert.ok(Math.abs(a.gross.opi2*2-normal.accrual[3].gross.opi2)<=1);assert.equal(r.people[0].events.find(e=>e.origin===2029&&e.type==='opi2').payYear,2030);conservation(r);});
test('2030 performance changes accrual but not cash through 2030',()=>{const s=defaults(),r=calculate(s);s.scenarios.middle.performance[2030]=900;const changed=calculate(s);assert.deepEqual(changed.cashflow.map(c=>c.netTotal),r.cashflow.map(c=>c.netTotal));assert.notEqual(changed.totals.netAccrual,r.totals.netAccrual);conservation(changed);});
test('PSU0 and unpaid cohorts preserve early cash years',()=>{const s=defaults(),r=calculate(s),down=calculate(s,s.scenarios.downturn);assert.deepEqual(r.cashflow.slice(0,3),down.cashflow.slice(0,3));const sc=copy(s.scenarios.downturn);sc.psuMode='zero';assert.deepEqual(calculate(s,sc).cashflow.slice(0,2),down.cashflow.slice(0,2));});
test('threshold equality pays and forced unpaid wins',()=>{const s=defaults();s.scenarios.middle.performance[2026]=200;assert.ok(calculate(s).accrual[0].gross.opi2>0);s.scenarios.middle.performance[2026]=199.9;assert.ok(calculate(s).accrual[0].reasons.includes('지급 기준 미달'));s.scenarios.middle.performance[2026]=400;s.scenarios.middle.unpaid[2026]=true;assert.equal(calculate(s).accrual[0].gross.opi2,0);assert.ok(calculate(s).accrual[0].reasons.includes('사용자 미지급 가정'));});
test('same-year and user-designated payment years retain full first-delivery taxation',()=>{const s=defaults();s.settings.opi2Delay=0;assert.ok(calculate(s).cashflow[0].net.opi2>0);s.settings.opi2PayYears[2026]=2032;const r=calculate(s),e=r.people[0].events.find(e=>e.origin===2026&&e.type==='opi2');assert.deepEqual(e.tranches.map(t=>t.year),[2032,2033,2034]);assert.ok(r.locked.unpaidStock>=e.net);conservation(r);});
test('narrowing to 2028–2030 retains entered 2026/27 cohorts and opening balance',()=>{const s=defaults(),r=calculate(s);s.startYear=2028;const window=calculate(s);assert.deepEqual(window.cashflow.map(c=>c.netTotal),r.cashflow.slice(2).map(c=>c.netTotal));assert.ok(window.opening.total>0);conservation(window);});
test('future salary serves taxes only; previous unentered OPI defaults to zero',()=>{const r=calculate(defaults()),p=r.people[0];assert.equal(p.taxLog.find(t=>t.year===2031).baseTax.pensionCap,79080000);assert.equal(p.cashflow[0].net.opi1,0);assert.equal(p.accrual.length,5);assert.ok(!p.cashflow.some(c=>c.year>2030));});
test('statutory pension and health caps plus work-deduction maximum',()=>{const t=defaults().settings.tax;assert.equal(taxAndInsurance(100000000,2026,t).pension,3693600);assert.equal(taxAndInsurance(2000000000,2026,t).health,55100880);assert.equal(workDeduction(1000000000),20000000);});
test('generic fixed allowance enters tax, bonus inclusion remains optional',()=>{const s=defaults();s.people[0].allowance=2400000;assert.equal(calculate(s).accrual[0].gross.opi1,42500000);assert.equal(calculate(s).people[0].taxLog[0].baseGross,87400000);s.people[0].includeAllowance=true;assert.equal(calculate(s).accrual[0].gross.opi1,43700000);});
test('nondivisible PSU share counts split equal value and locked shares stay out of cash',()=>{const s=defaults();s.people[0].grade='CL1·CL2';s.people[0].psuMultiplier=.5;s.people[0].psuPrice=250001;const r=calculate(s),psu=r.people[0].events.filter(e=>e.type==='psu');assert.equal(sum(psu.map(e=>e.gross)),25000100);assert.ok(Math.max(...psu.map(e=>e.gross))-Math.min(...psu.map(e=>e.gross))<=1);s.people[0].psuLock=4;const locked=calculate(s);assert.equal(sum(locked.cashflow.map(c=>c.net.psu)),0);conservation(locked);});
test('v2 JSON roundtrip, recomputation, validation and no extra private fields',()=>{const s=defaults();s.opi2Policy.mode='estimate';const d=exportData(s);d.annualLiquidCashflow[0].netTotal=1;d.input.unrecognizedPrivateData='discard';assert.deepEqual(parseImport(JSON.stringify(d)),s);assert.deepEqual(parseImport('\ufeff'+JSON.stringify(s)),s);for(const alter of [s=>s.startYear=2031,s=>s.endYear=2059,s=>s.people[0].salary=-1,s=>s.settings.opi2Base=0,s=>s.settings.tax.brackets[1][0]=1,s=>s.settings.opi2PayYears[2026]=2025]){const bad=copy(s);alter(bad);assert.throws(()=>parseImport(JSON.stringify(bad)));}});
test('legacy two-person JSON explicitly migrates first person only without mutating source',()=>{const old=defaults();old.schemaVersion=1;old.mode='household';old.people[0].name='예시 A';old.people[0].salary=72000000;old.people.push({...defaultPerson(2),name:'예시 B',salary:64000000});old.privateMetadata='discard';const original=JSON.stringify(old),imported=importConditions(original);assert.equal(imported.migrated,true);assert.ok(imported.notice.includes('첫 번째 개인'));assert.equal(imported.state.schemaVersion,2);assert.equal(imported.state.mode,'individual');assert.equal(imported.state.people.length,1);assert.equal(imported.state.people[0].salary,72000000);assert.equal(JSON.stringify(old),original);const d=exportData(imported.state);assert.equal(d.people.length,1);assert.ok(!JSON.stringify(d).includes('예시 B'));assert.ok(!JSON.stringify(d).includes('privateMetadata'));conservation(calculate(imported.state));});
test('multi-person v2 is rejected; calculation cannot reactivate combined mode',()=>{const s=defaults(),baseline=calculate(s);s.mode='household';s.people.push({...defaultPerson(2),salary:64000000});assert.throws(()=>validateState(s));assert.throws(()=>parseImport(JSON.stringify(s)));assert.throws(()=>calculate(s));assert.equal(baseline.people.length,1);});
test('explicit annual salary, individual growth and maximum cap',()=>{const s=defaults();s.people[0].growthByYear[2027]=.02;assert.equal(salaryAt(s.people[0],2027,s),86700000);s.people[0].cap=100000000;s.people[0].salaries[2028]=120000000;assert.equal(salaryAt(s.people[0],2028,s),100000000);});
test('25 varied configurations preserve individual tax and payment ledgers',()=>{for(let i=0;i<25;i++){const s=defaults();s.settings.opi2Delay=i%3;s.settings.opi1Delay=i%2;s.people[0].psuLock=i%4;s.people[0].salary=85000000+i*137;s.people[0].study[2029]=!!(i%2);s.scenarios.middle.performance[2027]=300+i*.5;if(i%4===0)s.startYear=2027;conservation(calculate(s));}});

test('invalid numeric values, malformed year maps and unsafe aggregates fail explicitly',()=>{for(const alter of [s=>s.people[0].salary=NaN,s=>s.people[0].growth=Infinity,s=>s.people[0].allowance=-1,s=>s.people[0].salaries=[],s=>s.people[0].growthByYear={oops:.05},s=>s.settings.opi2PayYears={2026:2025},s=>s.scenarios.middle.unpaid={2026:'true'}]){const s=defaults();alter(s);assert.throws(()=>calculate(s));}assert.throws(()=>sum([Number.MAX_SAFE_INTEGER,1]));assert.equal(mul(100000000,1e-7),10);});
test('all key option combinations preserve tax and timing ledgers',()=>{let count=0;for(const division of ['메모리','공통','파운드리·시스템LSI'])for(const study of [false,true])for(const includeAllowance of [false,true])for(const delay of [0,1,2])for(const zero of [false,true])for(const lock of [0,3]){const s=defaults();Object.assign(s.people[0],{division,includeAllowance,allowance:2400000,psuLock:lock});s.people[0].study[2028]=study;s.settings.opi2Delay=delay;s.settings.opi2PayYears[2029]=2033;s.scenarios.middle.psuMode=zero?'zero':'normal';s.people[0].salaries[2027]=90000000;s.people[0].cap=100000000;s.startYear=count%3===0?2028:2026;s.endYear=count%4===0?2033:2030;validateState(s);const r=calculate(s);conservation(r);const a=r.people[0].events.filter(e=>e.origin===2028);if(study){assert.equal(a.find(e=>e.type==='opi1').gross,0);assert.equal(a.find(e=>e.type==='tai').gross,0);}assert.ok(r.people[0].events.filter(e=>e.type==='psu').every(e=>e.tranches[0].year===e.payYear+lock));assert.ok(r.cashflow.every(c=>c.year>=s.startYear&&c.year<=s.endYear));count++;}assert.equal(count,144);});

test('pension employee rate stops at 6.5% after 2033; actual paid override is shared by base and full incomes',()=>{const s=defaults(),t=s.settings.tax;assert.equal(taxAndInsurance(85000000,2033,t).pensionRate,.065);assert.equal(taxAndInsurance(85000000,2040,t).pensionRate,.065);t.pensionPaidByYear[2026]=1200000;const r=calculate(s),log=r.people[0].taxLog.find(t=>t.year===2026);assert.equal(log.baseTax.pension,1200000);assert.equal(log.fullTax.pension,1200000);assert.equal(taxAndInsurance(85000000,2027,t).pension,3954000);conservation(r);assert.deepEqual(parseImport(JSON.stringify(s)),s);t.pensionPaidByYear[2026]=-1;assert.throws(()=>validateState(s));});

test('common coefficient applies to whole memory-equivalent OPI2 value',()=>{const s=defaults();s.people[0].division='메모리';const memory=calculate(s).accrual[0].gross.opi2;s.people[0].division='공통';assert.equal(calculate(s).accrual[0].gross.opi2,mul(memory,.7));s.people[0].division='파운드리·시스템LSI';assert.equal(calculate(s).accrual[0].gross.opi2,mul(memory,.3));});

// Historical model regression fixture; the public UI uses the simplified inputs.
function defaults(){const s=publicDefaults();s.opi2Policy.simpleInput=false;s.opi2Policy.donationRate=.002;for(const sc of Object.values(s.scenarios))sc.performance={2026:389,2027:567,2028:576,2029:518,2030:466};return s;}
