import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaults as publicDefaults,calculate,exportData,parseImport,sum,mul,split3,allocate} from '../dist/engine.js';
import {calculateIntegrated,awardIdentity,buildPolicyLedger,comparePlan} from '../dist/integrated.js';
import {unionExampleCheck} from '../dist/reference-check.js';
function toy(close=100000){const s=defaults();s.people[0].division='메모리';s.endYear=2026;s.people[0].includePSU=false;s.settings.opi1Rate=0;s.settings.taiRate=0;Object.assign(s.opi2Policy,{rateSource:'direct',rateScope:'personal',paymentRateByYear:{2026:1},workBonusByYear:{2026:15000000},vwapWeekByYear:{2026:100000},vwapMonthByYear:{2026:100000},vwapTwoMonthsByYear:{2026:100000},closingPriceByYear:{2026:close}});return s;}
function invariants(r){if(r.accounting.complete)assert.equal(r.accounting.difference,0);for(const e of r.events.filter(e=>e.type==='opi2')){assert.equal(e.identity.costIdentity.difference,0);if(e.net!==null){assert.equal(e.identity.valuationIdentityDifference,0);assert.equal(sum(e.tranches.map(t=>t.net)),e.snapshot.estimatedStockMarketValue);assert.equal(e.net,sum([e.snapshot.estimatedStockMarketValue,...e.settlements.map(t=>t.net)]));}assert.equal(e.snapshot.actualDeliveredShares,null);}for(const t of r.taxLog){assert.equal(sum(t.allocation.map(a=>a.finalTaxEstimate)),t.incrementTax);assert.equal(sum(t.allocation.map(a=>a.finalInsuranceEstimate)),t.incrementInsurance);}assert.equal(sum(r.cashflow.map(c=>c.netTotal)),r.totals.netLiquid);}
test('default full five-year model is usable with explicit forecasts, examples, and unconfirmed actual values',()=>{const s=defaults(),r=calculateIntegrated(s);assert.ok(r.complete);assert.ok(r.totals.netLiquid>0);assert.equal(r.accrual.length,5);assert.equal(r.events.filter(e=>e.type==='opi2').length,5);assert.equal(s.opi2Policy.workBonusByYear[2026],0);assert.equal(s.opi2Policy.vwapWeekByYear[2026],250000);assert.equal(s.opi2Policy.paymentDateByYear[2026],'2027-04-01');assert.equal(r.confirmed.annualCashflow,null);invariants(r);});
test('legacy forecast generates personal rate then applies independent new basis and CL4 factor once',()=>{const s=defaults();s.people[0].division='메모리';s.endYear=2026;s.scenarios.middle.performance[2026]=300;s.opi2Policy.workBonusByYear[2026]=15000000;let r=calculateIntegrated(s),e=r.events.find(e=>e.type==='opi2');assert.equal(e.gross,635294118);s.people[0].division='공통';e=calculateIntegrated(s).events.find(e=>e.type==='opi2');assert.equal(e.gross,444705882);s.opi2Policy.gradeByYear[2026]='CL4';s.opi2Policy.ratingByYear[2026]='EM';r=calculateIntegrated(s);e=r.events.find(e=>e.type==='opi2');assert.equal(e.gross,622588235);assert.equal(r.events.find(e=>e.type==='opi1').gross,42500000);assert.equal(r.events.find(e=>e.type==='tai').gross,8500000);assert.equal(r.accrual[0].gross.salary,85000000);invariants(r);});
test('direct100% is independent of profit forecast and personally scoped coefficient is not repeated',()=>{const s=toy();s.people[0].division='공통';s.scenarios.middle.performance[2026]=0;const e=calculateIntegrated(s).events.find(e=>e.type==='opi2');assert.equal(e.gross,100000000);s.opi2Policy.rateScope='memory';assert.equal(calculateIntegrated(s).events.find(e=>e.type==='opi2').gross,70000000);});
test('same-price toy identity separates stock45.333m from settlement30.467m and preserves75.8m',()=>{const r=buildPolicyLedger(toy()).rows[0],c=r.selectedWithholdingScenario;const a=awardIdentity({gross:r.preliminaryGross,donation:c.donation,withheldTax:c.tax,withheldInsurance:c.insurance,stockBudget:c.stockBudget,stockValue:c.stockBudget,finalTax:20000000,finalInsurance:4000000});assert.equal(c.netFractionalShares,453.33);assert.equal(c.stockBudget,45333000);assert.equal(a.settlementTax+a.settlementInsurance,30467000);assert.equal(a.finalEconomicValue,75800000);assert.equal(a.marketAdjustment,0);assert.equal(a.valuationIdentityDifference,0);const stock=split3(c.stockBudget),cash={2027:stock[0],2028:stock[1]+a.settlementTax+a.settlementInsurance,2029:stock[2]};assert.deepEqual(cash,{2027:15111000,2028:45578000,2029:15111000});});
test('different-price toy uses netQ market gain, not grossQ gain, and final value82.8866m',()=>{const r=buildPolicyLedger(toy(120000)).rows[0],c=r.selectedWithholdingScenario,stock=mul(c.stockBudget,1.2);assert.equal(c.netFractionalShares,354.33);assert.equal(c.stockBudget,35433000);assert.equal(stock,42519600);const a=awardIdentity({gross:r.preliminaryGross,donation:c.donation,withheldTax:c.tax,withheldInsurance:c.insurance,stockBudget:c.stockBudget,stockValue:stock,finalTax:20000000,finalInsurance:4000000});assert.equal(a.settlementTax+a.settlementInsurance,40367000);assert.equal(a.marketAdjustment,7086600);assert.equal(a.finalEconomicValue,82886600);assert.equal(a.valuationIdentityDifference,0);assert.notEqual(a.finalEconomicValue,100000000-200000-20000000-4000000);});
test('negative stock budget retains4.167m shortfall, null stock, and incomplete total warning',()=>{const r=calculateIntegrated(toy(200000)),e=r.events.find(e=>e.type==='opi2');assert.equal(e.snapshot.benchmarkStockBudget,-4167000);assert.equal(e.snapshot.fundingShortfall,4167000);assert.equal(e.snapshot.estimatedStockMarketValue,null);assert.equal(e.net,null);assert.equal(r.complete,false);assert.equal(r.accounting.complete,false);assert.equal(r.calculationWarnings[0].fundingShortfall,4167000);assert.equal(e.tranches.length,0);});
test('annual tax uses all taxable amounts once; prewithholding never deducted again from net compensation',()=>{const s=toy(),r=calculateIntegrated(s),e=r.events.find(e=>e.type==='opi2'),t=r.taxLog.find(t=>t.year===2027);assert.equal(t.bonus,100000000);assert.equal(e.finalTaxEstimate,t.incrementTax);assert.equal(e.finalInsuranceEstimate,t.incrementInsurance);assert.equal(e.net,sum([e.snapshot.estimatedStockMarketValue,e.snapshot.withheldTax,e.snapshot.withheldInsurance,-e.finalTaxEstimate,-e.finalInsuranceEstimate]));assert.equal(e.identity.valuationIdentityDifference,0);invariants(r);});
test('higher close reports higher Y; fractional stock quantity remains unaffected by later settlement settings',()=>{const s=toy(120000),a=calculateIntegrated(s),e=a.events.find(e=>e.type==='opi2');assert.equal(e.taxableIncome,120000000);assert.equal(e.snapshot.estimatedStockMarketValue,42519600);s.opi2Policy.taxSettlementYearByOrigin[2026]=2035;s.opi2Policy.insuranceSettlementYearByOrigin[2026]=2036;const b=calculateIntegrated(s),other=b.events.find(e=>e.type==='opi2');assert.deepEqual(other.snapshot,e.snapshot);assert.equal(other.net,e.net);assert.deepEqual(other.settlements.map(t=>t.year),[2035,2036]);invariants(b);});
test('refund and extra charge are separately signed cash events and outstanding claims/liabilities',()=>{const s=toy();s.opi2Policy.withholdingTaxRate=.05;const r=calculateIntegrated(s),e=r.events.find(e=>e.type==='opi2');assert.ok(e.settlements.find(t=>t.kind==='tax').net<0);assert.ok(r.locked.settlementPayable>0);assert.ok(r.locked.settlementEvents.some(t=>t.net<0));invariants(r);const normal=calculateIntegrated(toy());assert.ok(normal.locked.settlementReceivable>0);invariants(normal);});
test('2030 origin contributes accrued value and outstanding settlement but zero liquidity through2030',()=>{const s=defaults(),a=calculateIntegrated(s);s.scenarios.middle.performance[2030]*=2;const b=calculateIntegrated(s);assert.deepEqual(b.cashflow,a.cashflow);assert.ok(b.totals.netAccrual>a.totals.netAccrual);assert.ok(b.locked.unpaidStock>a.locked.unpaidStock);assert.ok(b.locked.settlementReceivable>a.locked.settlementReceivable);const cohort=b.events.find(e=>e.type==='opi2'&&e.origin===2030);assert.equal(cohort.payYear,2031);assert.ok(cohort.settlements.every(t=>t.year===2032));invariants(b);});
test('2030 settlement boundary excludes later cash but preserves remaining receivable/payable separately',()=>{const s=defaults();s.opi2Policy.taxSettlementYearByOrigin[2028]=2031;const r=calculateIntegrated(s);assert.ok(r.locked.settlementEvents.some(t=>t.origin===2028&&t.kind==='tax'));assert.ok(!r.cashflow.at(-1).details.some(t=>t.origin===2028&&t.kind==='tax'));invariants(r);});
test('narrower period preserves prior cohorts, outstanding settlement, and opening identity',()=>{const s=defaults(),all=calculateIntegrated(s);s.startYear=2028;const r=calculateIntegrated(s);assert.deepEqual(r.cashflow,all.cashflow.slice(2).map((c,i)=>({...c,cumulative:sum(all.cashflow.slice(2,3+i).map(v=>v.netTotal))})));assert.ok(r.opening.total>0);assert.ok(r.cashflow[0].details.some(t=>t.origin===2026&&t.type==='settlement'));invariants(r);});
test('missing inputs and disabled future repetition are pending exclusions, not silently confirmed zero awards',()=>{const s=defaults();delete s.opi2Policy.workBonusByYear[2026];s.opi2Policy.repeatFutureYears=false;const r=calculateIntegrated(s);assert.equal(r.complete,false);assert.equal(r.pendingOrigins.length,5);assert.ok(r.accrual.every(a=>a.opi2Pending));assert.ok(r.accrual.every(a=>a.reasons.some(v=>v.includes('0원 확정 아님'))));assert.ok(r.totals.netLiquid>0);invariants(r);});
test('forced zero and profit threshold reasons survive direct/forecast calculation',()=>{const s=defaults();s.scenarios.middle.unpaid[2028]=true;s.scenarios.middle.performance[2029]=99;const r=calculateIntegrated(s);assert.equal(r.events.find(e=>e.type==='opi2'&&e.origin===2028).gross,0);assert.equal(r.events.find(e=>e.type==='opi2'&&e.origin===2028).reason,'사용자 미지급 가정');assert.equal(r.events.find(e=>e.type==='opi2'&&e.origin===2029).reason,'지급 기준 미달');invariants(r);});
test('study adjusts OPI2 once and keeps PSU exempt from special prewithholding',()=>{const s=defaults(),a=calculateIntegrated(s);s.people[0].study[2026]=true;const b=calculateIntegrated(s);assert.equal(b.events.find(e=>e.type==='opi2'&&e.origin===2026).gross,mul(a.events.find(e=>e.type==='opi2'&&e.origin===2026).gross,.5));assert.equal(b.events.find(e=>e.type==='opi1'&&e.origin===2026).gross,0);assert.equal(b.events.find(e=>e.type==='tai'&&e.origin===2026).gross,0);assert.ok(b.events.filter(e=>e.type==='psu').every(e=>e.snapshot===undefined&&e.settlements===undefined));invariants(b);});
test('JSON/scenario exports include annual totals, settlement details and confirmed-null fields',()=>{const s=defaults(),d=exportData(s);assert.equal(d.resultModel,'policy_integrated_estimate');assert.equal(d.annualLiquidCashflow.length,5);assert.ok(d.scenarioComparison.downturn.totals.netLiquid<d.scenarioComparison.middle.totals.netLiquid);assert.ok(d.cashSettlementAfterPeriod.length>0);assert.equal(d.confirmed.annualCashflow,null);assert.deepEqual(parseImport(JSON.stringify(d)),s);invariants(calculateIntegrated(parseImport(JSON.stringify(d))));});
test('invalid settlement year earlier than payment is rejected',()=>{const s=toy();s.opi2Policy.taxSettlementYearByOrigin[2026]=2026;assert.throws(()=>calculateIntegrated(s),/정산연도/);});
test('deterministic largest-remainder allocation remains independent of event order for each tax component',()=>{const weights=[{id:'psu',weight:50000000},{id:'opi2',weight:300000000},{id:'opi1',weight:42500000}];for(const total of [12345678,9999991]){const a=allocate(total,weights),back=[...weights].reverse(),b=allocate(total,back);assert.deepEqual(Object.fromEntries(weights.map((w,i)=>[w.id,a[i]])),Object.fromEntries(back.map((w,i)=>[w.id,b[i]])));assert.equal(sum(a),total);}});
test('144 integrated combinations preserve accrual, stock, tax and settlement ledgers',()=>{let n=0;for(const division of ['메모리','공통','파운드리·시스템LSI'])for(const study of [false,true])for(const close of [200000,250000,300000])for(const delay of [0,1])for(const psu of [0,2])for(const source of ['legacy','direct']){const s=defaults();s.people[0].division=division;s.people[0].study[2026]=study;s.people[0].psuMultiplier=psu;s.opi2Policy.closingPriceByYear[2026]=close;s.opi2Policy.taxSettlementDelay=delay;s.opi2Policy.insuranceSettlementDelay=delay;s.opi2Policy.rateSource=source;if(source==='direct')s.opi2Policy.paymentRateByYear=Object.fromEntries([2026,2027,2028,2029,2030].map(y=>[y,1]));invariants(calculateIntegrated(s));n++;}assert.equal(n,144);});

test('370tr/82m user-relayed union examples are compared without calibrating the formula',()=>{const r=unionExampleCheck();assert.deepEqual(r.rows.map(a=>a.estimatedGross),[642494118,449745882,192748235]);assert.deepEqual(r.rows.map(a=>a.requiredWorkBonusIfTargetIsPretax),[13720721,14632347,20102102]);assert.equal(r.memoryTargetImpliedCommon,525000000);assert.equal(r.memoryTargetImpliedFoundry,225000000);assert.equal(r.foundryToMemoryTargetRatio,.32);assert.deepEqual(r.rows.map(a=>a.coefficient),[1,.7,.3]);});

test('new integrated middle scenario regression excludes beyond2030 liquidity and includes donation/settlement',()=>{const r=calculateIntegrated(defaults());assert.deepEqual(r.cashflow.map(c=>c.netTotal),[72823356,172113522,363826488,502298769,549349289]);assert.equal(r.totals.netLiquid,1660411424);assert.equal(r.totals.netAccrual,2478298760);invariants(r);});

test('integrated2028/29 unpaid plus PSU600 scenario regression',()=>{const s=defaults(),r=calculateIntegrated(s,s.scenarios.downturn);assert.deepEqual(r.cashflow.map(c=>c.netTotal),[72823356,172113522,363826488,388427580,257474871]);assert.equal(r.totals.netLiquid,1254665817);invariants(r);});

test('integrated2028/29 unpaid plus PSU0 scenario regression',()=>{const s=defaults(),scenario=structuredClone(s.scenarios.downturn);scenario.psuMode='zero';const r=calculateIntegrated(s,scenario);assert.deepEqual(r.cashflow.map(c=>c.netTotal),[72823356,172113522,337071407,360793625,228881160]);assert.equal(r.totals.netLiquid,1171683070);invariants(r);});

test('missing VWAP/close stays pending with warning while known salary and other cohorts remain usable',()=>{const s=defaults();delete s.opi2Policy.vwapWeekByYear[2026];delete s.opi2Policy.closingPriceByYear[2027];const r=calculateIntegrated(s);assert.equal(r.complete,false);assert.deepEqual(r.pendingOrigins.map(a=>a.origin),[2026,2027]);assert.ok(r.accrual[0].opi2Pending);assert.ok(r.totals.netLiquid>0);assert.equal(r.confirmed.deliveredShares,null);invariants(r);});

// Historical model regression fixture; the public UI uses the simplified inputs.
function defaults(){const s=publicDefaults();s.opi2Policy.simpleInput=false;return s;}
