import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaults,policyDraft,parseImport,exportData,mul,sum} from '../dist/engine.js';
import {validatePolicy,plusYears,dateValid,RATINGS} from '../dist/policy.js';
import {policyInputHTML,policyReviewHTML} from '../dist/policy-ui.js';
function filled(){const s=defaults();s.endYear=2026;s.people[0].division='메모리';Object.assign(s.opi2Policy,{gradeByYear:{2026:'CL3'},workBonusByYear:{2026:15000000},paymentRateByYear:{2026:1},vwapWeekByYear:{2026:100000},vwapMonthByYear:{2026:100000},vwapTwoMonthsByYear:{2026:100000},closingPriceByYear:{2026:100000},paymentDateByYear:{2026:'2027-04-01'},paymentDateConfirmedByYear:{2026:true}});return s;}
function conserve(row){for(const c of row.withholdingAlternatives){assert.equal(sum([c.tax,c.insurance,c.donation,c.stockBudget]),row.preliminaryGross);assert.ok([c.tax,c.insurance,c.donation,c.stockBudget].every(Number.isSafeInteger));if(c.stockBudget>=0)assert.equal(sum(c.releaseExamples.map(t=>t.amount)),c.stockBudget);assert.equal(c.actualDeliveredShares,null);assert.equal(c.finalAnnualTax,null);assert.equal(c.laterCashSettlement,null);}assert.equal(row.withholding,null);assert.equal(row.reportedEmploymentIncome,null);assert.equal(row.confirmedLiquidCashflow,null);assert.ok(row.releases.every(t=>t.amount===null));}
test('missing definitions produce null confirmed results, not zero or automatic TAI/OPI1 substitution',()=>{const missing=defaults();missing.opi2Policy.workBonusByYear={};const r=policyDraft(missing);assert.equal(r.excludedFromFinalAnnualTotals,true);assert.ok(r.rows.every(a=>a.workBonus===null&&a.preliminaryGross===null&&a.reportedEmploymentIncome===null&&a.confirmedCompensation===null));assert.ok(!r.rows[0].reasons.includes('업무성과급 정의 확인 대기'));assert.equal(defaults().opi2Policy.workBonusDefinition,'confirmed_separate');assert.equal(defaults().opi2Policy.reportedSharesDefinition,'gross_equivalent');assert.equal(r.rows[0].reportedSharesDefinitionConfirmed,false);});
test('base is separate work bonus plus 2026 contractual salary; allowance remains separate',()=>{const s=filled();s.people[0].allowance=2400000;const r=policyDraft(s).rows[0];assert.equal(r.basis,100000000);assert.equal(r.preliminaryGross,100000000);assert.equal(r.workBonus,15000000);assert.ok(r.pending);conserve(r);});
test('G100m/R=C100k example preserves three alternatives without asserting company confirmation',()=>{const r=policyDraft(filled()).rows[0],[a,b,c]=r.withholdingAlternatives;assert.equal(a.stockBudget,45333000);assert.equal(a.netFractionalShares,453.33);assert.ok(Math.abs(b.reportedFractionalShares-634.334448)<.000001);assert.ok(Math.abs(c.reportedFractionalShares-646.092693)<.000001);assert.equal(r.withholding,null);assert.equal(r.shares.actualDeliveredShares,null);conserve(r);});
test('CL4 ratings multiply payout only for CL4; common is whole memory-equivalent70%',()=>{for(const [rating,factor]of Object.entries(RATINGS)){const s=filled();s.opi2Policy.gradeByYear[2026]='CL4';s.opi2Policy.ratingByYear[2026]=rating;assert.equal(policyDraft(s).rows[0].preliminaryGross,mul(100000000,factor));s.people[0].division='공통';assert.equal(policyDraft(s).rows[0].preliminaryGross,mul(100000000,factor,.7));s.opi2Policy.gradeByYear[2026]='CL2';assert.equal(policyDraft(s).rows[0].preliminaryGross,70000000);}});
test('CL1 and missing CL4 rating cannot produce even a gross preview',()=>{const s=filled();s.opi2Policy.gradeByYear[2026]='CL1';assert.equal(policyDraft(s).rows[0].preliminaryGross,null);s.opi2Policy.gradeByYear[2026]='CL4';assert.equal(policyDraft(s).rows[0].preliminaryGross,null);});
test('three VWAP prices use exact mean fraction and closing price stays separate',()=>{const s=filled();s.opi2Policy.vwapWeekByYear[2026]=99999;s.opi2Policy.vwapMonthByYear[2026]=100000;s.opi2Policy.vwapTwoMonthsByYear[2026]=100002;s.opi2Policy.closingPriceByYear[2026]=125000;const r=policyDraft(s).rows[0];assert.deepEqual(r.prices.mean,{numerator:300001,denominator:3});assert.equal(r.prices.closingPrice,125000);assert.ok(r.withholdingAlternatives[0].reportedEmploymentIncomeExample>r.preliminaryGross);conserve(r);delete s.opi2Policy.vwapWeekByYear[2026];assert.equal(policyDraft(s).rows[0].prices.mean,null);assert.equal(policyDraft(s).rows[0].withholdingAlternatives.length,0);});
test('sale limits start on real delivery date; missing actual day never gets invented',()=>{const s=filled(),r=policyDraft(s).rows[0];assert.deepEqual(r.releases.map(t=>t.availableDate),['2027-04-01','2028-04-01','2029-04-01']);delete s.opi2Policy.paymentDateByYear[2026];const pending=policyDraft(s).rows[0];assert.equal(pending.payment.actualDate,null);assert.equal(pending.payment.expectedYear,2027);assert.ok(pending.releases.every(t=>t.availableDate===null));assert.equal(plusYears('2028-02-29',1),'2029-02-28');assert.ok(!dateValid('2027-02-29'));});
test('future repetition is opt-in, not a confirmed future company rule',()=>{const s=filled();s.endYear=2027;s.opi2Policy.repeatFutureYears=false;delete s.opi2Policy.expectedPaymentYearByYear[2027];delete s.opi2Policy.paymentDateByYear[2027];for(const key of ['gradeByYear','workBonusByYear','paymentRateByYear','vwapWeekByYear','vwapMonthByYear','vwapTwoMonthsByYear','closingPriceByYear'])s.opi2Policy[key][2027]=s.opi2Policy[key][2026];const r=policyDraft(s).rows[1];assert.equal(r.preliminaryGross,null);assert.equal(r.payment.expectedYear,null);s.opi2Policy.repeatFutureYears=true;const future=policyDraft(s).rows[1];assert.ok(future.preliminaryGross>0);assert.equal(future.futureAssumption,true);assert.equal(future.payment.expectedYear,2028);assert.equal(future.confirmedLiquidCashflow,null);});
test('donations use gross base in 0.2% steps; withholding includes no pension',()=>{for(const rate of [.002,.004,.006,.008,.01]){const s=filled();s.opi2Policy.donationRate=rate;const r=policyDraft(s).rows[0];assert.ok(r.withholdingAlternatives.every(c=>c.donation===mul(100000000,rate)));assert.equal(r.grossDeductionExample.pensionIncluded,false);conserve(r);}const s=filled();s.opi2Policy.donationRate=.003;assert.throws(()=>validatePolicy(s.opi2Policy));});
test('higher close price can make one gross-share candidate unfunded; no silent clamp',()=>{const s=filled();s.opi2Policy.closingPriceByYear[2026]=300000;const r=policyDraft(s).rows[0],a=r.withholdingAlternatives[0];assert.ok(a.stockBudget<0);assert.equal(a.releaseExamples.length,0);assert.equal(a.netFractionalShares,null);conserve(r);});
test('policy JSON input roundtrip preserves inputs and recomputes discarded results',()=>{const s=filled(),d=exportData(s);d.opi2PolicyReview.rows[0].preliminaryGross=1;assert.deepEqual(parseImport(JSON.stringify(d)),s);const old=defaults();delete old.opi2Policy;const migrated=parseImport(JSON.stringify(old));assert.equal(migrated.opi2Policy.mode,'review');assert.equal(migrated.opi2Policy.workBonusDefinition,'confirmed_separate');});
test('NaN, negative bonus, zero prices, malformed dates/maps, invalid grade and unsupported donation fail',()=>{for(const edit of [p=>p.workBonusByYear[2026]=-1,p=>p.paymentRateByYear[2026]=NaN,p=>p.vwapWeekByYear[2026]=0,p=>p.closingPriceByYear[2026]=Infinity,p=>p.paymentDateByYear[2026]='2027-02-29',p=>p.gradeByYear[2026]='CL5',p=>p.ratingByYear[2026]='BAD',p=>p.paymentDateByYear=[],p=>p.workBonusByYear={oops:1}]){const s=filled();edit(s.opi2Policy);assert.throws(()=>policyDraft(s));}});
test('rendered policy controls include all required independent inputs and no family UI',()=>{const field=(label,path)=>`<input aria-label="${label}" data-path="${path}">`,select=(label,path)=>`<select aria-label="${label}" data-path="${path}"></select>`,check=(label,path)=>`<input type="checkbox" aria-label="${label}" data-path="${path}">`,s=filled(),html=policyInputHTML(s,{field,select,check,years:s=>[2026],escape:String});for(const key of ['workBonusByYear','gradeByYear','ratingByYear','paymentRateByYear','paymentDateByYear','paymentDateConfirmedByYear','vwapWeekByYear','vwapMonthByYear','vwapTwoMonthsByYear','closingPriceByYear','donationRate'])assert.ok(html.includes('opi2Policy.'+key));assert.ok(!/우리 부부|가구 합산|아내/.test(html));const review=policyReviewHTML(policyDraft(s),{amount:v=>String(v),escape:String,warning:()=>'<p>예상치이며 실제 지급액·세금과 다를 수 있음</p>'});assert.ok(review.includes('최종 연간 세후 현금흐름이 아닙니다'));assert.ok(review.includes('가정 A'));assert.ok(review.includes('가정 B'));assert.ok(review.includes('가정 C'));});
test('150 option combinations keep illustrative ledgers separate and preserve every won',()=>{let n=0;for(const division of ['메모리','공통','파운드리·시스템LSI'])for(const rating of Object.keys(RATINGS))for(const donation of [.002,.004,.006,.008,.01])for(const study of [false,true]){const s=filled();s.people[0].division=division;s.people[0].study[2026]=study;s.opi2Policy.gradeByYear[2026]='CL4';s.opi2Policy.ratingByYear[2026]=rating;s.opi2Policy.donationRate=donation;s.opi2Policy.closingPriceByYear[2026]=100001;s.opi2Policy.vwapTwoMonthsByYear[2026]=99999;conserve(policyDraft(s).rows[0]);n++;}assert.equal(n,150);});

test('entered hypothetical date remains an assumption until explicitly confirmed',()=>{const s=filled();s.opi2Policy.paymentDateConfirmedByYear[2026]=false;const r=policyDraft(s).rows[0];assert.equal(r.payment.actualDate,null);assert.equal(r.payment.assumedDate,'2027-04-01');assert.equal(r.payment.exactDateConfirmed,false);assert.ok(r.releases.every(t=>t.availableDate===null));assert.deepEqual(r.releases.map(t=>t.assumedAvailableDate),['2027-04-01','2028-04-01','2029-04-01']);const l=policyDraft(s);assert.equal(l.payoutSnapshot,null);assert.equal(l.cashSettlementLedger.events,null);assert.equal(l.cashSettlementLedger.doesNotRewriteDeliveredShares,true);});

test('confirmed prior-year work bonus is a basis input only and adds no separate cash event',()=>{const s=filled(),r=policyDraft(s).rows[0];assert.equal(s.opi2Policy.workBonusDefinition,'confirmed_separate');assert.ok(r.workBonusInputPurpose.includes('전년도 성과'));assert.ok(r.workBonusInputPurpose.includes('별도 현금항목으로 재합산하지 않음'));assert.ok(!r.reasons.some(v=>v.includes('업무성과급 정의 확인 대기')));const d=exportData(s);assert.equal(d.annualLiquidCashflow.length,1);assert.equal(d.annualAccrualCompensation.length,1);assert.ok(!d.annualLiquidCashflow[0].details.some(e=>e.type==='workBonus'));assert.equal(d.opi2PolicyReview.rows[0].basis,100000000);const old=structuredClone(s);old.opi2Policy.workBonusDefinition='pending';assert.equal(parseImport(JSON.stringify(old)).opi2Policy.workBonusDefinition,'confirmed_separate');});

test('gross-share default is inference only; closing price affects reported income independently from stock basis',()=>{const s=filled();s.opi2Policy.closingPriceByYear[2026]=110000;const r=policyDraft(s).rows[0],a=r.selectedWithholdingScenario;assert.equal(s.opi2Policy.reportedSharesDefinition,'gross_equivalent');assert.equal(r.reportedSharesDefinitionConfirmed,false);assert.equal(a.reportedFractionalShares,1000);assert.equal(a.reportedEmploymentIncomeExample,110000000);assert.equal(a.tax,54450000);assert.equal(a.insurance,4967000);assert.equal(a.stockBudget,40383000);assert.equal(a.netFractionalShares,403.83);assert.equal(r.shares.fractionalNetShares,403.83);assert.equal(r.reportedEmploymentIncome,null);assert.equal(a.confirmed,false);conserve(r);s.opi2Policy.taxWithholdingBase='gross';const alternative=policyDraft(s).rows[0].selectedWithholdingScenario;assert.equal(alternative.tax,49500000);assert.equal(alternative.stockBudget,45333000);});

test('all eight combinations of reported quantity and independent withholding bases remain explicit assumptions',()=>{const s=filled();s.opi2Policy.closingPriceByYear[2026]=110000;const rows=[];for(const reported of ['gross_equivalent','net_delivered'])for(const taxBase of ['gross','employment_income'])for(const insuranceBase of ['gross','employment_income']){s.opi2Policy.reportedSharesDefinition=reported;s.opi2Policy.taxWithholdingBase=taxBase;s.opi2Policy.insuranceWithholdingBase=insuranceBase;const r=policyDraft(s).rows[0];assert.equal(r.withholdingAlternatives.length,8);assert.equal(r.selectedWithholdingScenario.reportedDefinition,reported);assert.equal(r.selectedWithholdingScenario.taxBase,taxBase);assert.equal(r.selectedWithholdingScenario.insuranceBase,insuranceBase);assert.equal(r.selectedWithholdingScenario.assumptionOnly,true);conserve(r);rows.push(r);}assert.equal(rows.length,8);});

test('unsafe closing-price income fails instead of emitting an imprecise won number',()=>{const s=filled();s.opi2Policy.workBonusByYear[2026]=100000000000;for(const k of ['vwapWeekByYear','vwapMonthByYear','vwapTwoMonthsByYear'])s.opi2Policy[k][2026]=1;s.opi2Policy.closingPriceByYear[2026]=10000000;s.opi2Policy.withholdingTaxRate=0;s.opi2Policy.withholdingInsuranceRate=0;assert.throws(()=>policyDraft(s),/범위/);});
