import {test} from 'node:test';
import assert from 'node:assert/strict';
import {defaults,parseImport,exportData,sum} from '../dist/engine.js';
import {normalizeSimpleState} from '../dist/policy.js';
import {calculatePlan,comparePlan} from '../dist/integrated.js';
const award=(s,y=2026)=>calculatePlan(s).events.find(e=>e.type==='opi2'&&e.origin===y);
function conserve(r){assert.equal(r.accounting.difference,0);assert.ok(r.complete);for(const t of r.taxLog){assert.equal(sum(t.allocation.map(a=>a.finalTaxEstimate)),t.incrementTax);assert.equal(sum(t.allocation.map(a=>a.finalInsuranceEstimate)),t.incrementInsurance);}for(const e of r.events.filter(x=>x.type==='opi2')){assert.equal(e.identity.costIdentity.difference,0);assert.equal(sum(e.tranches.map(t=>t.net)),e.snapshot.estimatedStockMarketValue);assert.equal(e.net,sum([e.snapshot.estimatedStockMarketValue,...e.settlements.map(t=>t.net)]));}}
test('manual final gross bypasses division, CL4 rating, study, work bonus and forecast factors',()=>{const s=defaults();s.opi2Policy.manualGrossByYear[2026]=100000001;s.scenarios.middle.unpaid[2026]=true;s.scenarios.middle.opi2Factor=.5;s.people[0].study[2026]=true;Object.assign(s.opi2Policy,{gradeByYear:{2026:'CL4'},ratingByYear:{2026:'EM'},workBonusByYear:{2026:90000000},rateSource:'direct',paymentRateByYear:{2026:50}});for(const division of ['메모리','공통','파운드리·시스템LSI']){s.people[0].division=division;assert.equal(award(s).gross,100000001);conserve(calculatePlan(s));}});
test('explicit zero is an unpaid award; blank uses automatic forecast and study halves only automatic',()=>{const s=defaults();assert.equal(award(s).gross,490140000);s.opi2Policy.manualGrossByYear[2026]=0;assert.equal(award(s).gross,0);assert.equal(award(s).reason,'사용자 입력 0원');delete s.opi2Policy.manualGrossByYear[2026];s.people[0].study[2026]=true;assert.equal(award(s).gross,245070000);assert.equal(award(s).policyRow.inputMethod,'automatic_forecast');});
test('all five donations use gross and immediately change stock budget without double final tax',()=>{const s=defaults();s.opi2Policy.manualGrossByYear[2026]=100000000;let finalTax;for(const rate of [.002,.004,.006,.008,.01]){s.opi2Policy.donationRate=rate;const e=award(s);assert.equal(e.snapshot.withheldTax,49500000);assert.equal(e.snapshot.withheldInsurance,4967000);assert.equal(e.snapshot.donation,100000000*rate);assert.equal(e.snapshot.estimatedStockMarketValue,45533000-100000000*rate);if(finalTax!==undefined)assert.equal(e.deduction,finalTax);finalTax=e.deduction;assert.equal(e.net,100000000-e.snapshot.donation-e.deduction);}});
test('old saved choices are harmless after browser migration and retain salary, PSU and final gross',()=>{const s=defaults();s.people[0].salary=87000000;s.people[0].psuPrice=175000;s.opi2Policy.manualGrossByYear={2026:123456789};Object.assign(s.opi2Policy,{simpleInput:false,mode:'estimate',taxWithholdingBase:'employment_income',reportedSharesDefinition:'net_delivered',repeatFutureYears:false,workBonusByYear:{2026:99999999},gradeByYear:{2026:'CL4'},ratingByYear:{2026:'EM'},closingPriceByYear:{2026:900000},vwapWeekByYear:{2026:50000},taxSettlementYearByOrigin:{2026:2040},insuranceSettlementDelay:8});s.settings.opi2Delay=0;s.settings.opi2PayYears={2026:2026};const m=normalizeSimpleState(parseImport(JSON.stringify(s)));assert.equal(m.people[0].salary,87000000);assert.equal(m.people[0].psuPrice,175000);assert.equal(m.opi2Policy.workBonusByYear[2026],0);assert.deepEqual(m.opi2Policy.ratingByYear,{});const e=award(m);assert.equal(e.gross,123456789);assert.equal(e.payYear,2027);assert.equal(e.taxableIncome,e.gross);assert.ok(e.settlements.every(t=>t.year===2028));assert.equal(e.marketAdjustment,0);});
test('2030 final amount increases accrual but cannot enter cash through2030',()=>{const s=defaults(),before=calculatePlan(s);s.opi2Policy.manualGrossByYear[2030]=999999999;const after=calculatePlan(s);assert.equal(after.totals.netLiquid,before.totals.netLiquid);assert.notEqual(after.totals.netAccrual,before.totals.netAccrual);assert.equal(award(s,2030).payYear,2031);conserve(after);});
test('five-year scenarios and shortened period preserve stock, settlement and tax accounting',()=>{for(const donation of [.002,.004,.006,.008,.01]){const s=defaults();s.opi2Policy.donationRate=donation;s.opi2Policy.manualGrossByYear={2026:100000007,2027:200000011,2030:0};for(const r of Object.values(comparePlan(s)))conserve(r);s.startYear=2028;conserve(calculatePlan(s));}});
test('single example price does not change gross, withholding or cash totals',()=>{const s=defaults();s.opi2Policy.manualGrossByYear[2026]=100000000;const before=award(s);s.people[0].includePSU=false;const cashBefore=calculatePlan(s).totals.netLiquid;s.people[0].psuPrice=177777;const after=award(s);assert.equal(after.gross,before.gross);assert.equal(after.snapshot.estimatedStockMarketValue,before.snapshot.estimatedStockMarketValue);assert.equal(after.marketAdjustment,0);assert.equal(calculatePlan(s).totals.netLiquid,cashBefore);});
test('JSON exports simple inputs and fixed assumptions, never obsolete alternative selections',()=>{const s=defaults();s.opi2Policy.manualGrossByYear={2026:0,2027:123456789};const d=exportData(s);assert.deepEqual(Object.keys(d.input.opi2Policy).sort(),['donationRate','manualGrossByYear','simpleInput']);assert.equal(d.assumptions.policy.withholdingBase,'gross');assert.equal(d.assumptions.policy.workBonus,0);const text=JSON.stringify(d);for(const hidden of ['workBonusByYear','ratingByYear','gradeByYear','withholdingAlternatives','vwapWeekByYear','paymentRateByYear'])assert.ok(!text.includes(hidden));const imported=normalizeSimpleState(parseImport(text));assert.deepEqual(imported.opi2Policy.manualGrossByYear,s.opi2Policy.manualGrossByYear);assert.equal(calculatePlan(imported).totals.netLiquid,calculatePlan(s).totals.netLiquid);});
test('negative or noninteger final amount and unsupported donation are rejected',()=>{for(const gross of [-1,.1,NaN,Infinity]){const s=defaults();s.opi2Policy.manualGrossByYear[2026]=gross;assert.throws(()=>calculatePlan(s));}const s=defaults();s.opi2Policy.donationRate=.003;assert.throws(()=>calculatePlan(s));});
